<?php
$this->headScript()->appendFile('http://code.jquery.com/jquery-1.8.3.js', 'text/javascript');
$this->headScript()->appendFile('http://code.jquery.com/ui/1.10.0/jquery-ui.js', 'text/javascript');
$this->headLink()->appendStylesheet('http://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css');

$this->headScript()->appendScript(
    '$(function(){
        $("a.ui-button").button();
    });', 'text/javascript'
);

?>

<h1>Welcome to Users Module</h1>
<a href="/users/login" class="ui-button">Login</a>
<a href="/users/register" class="ui-button">New User Registration</a>